- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install packages
    apt:
      name:
        - btop
        - tmux
        - micro
        - bash
        - neovim
        - neofetch
        
      
     
